import type { AnalyticsSummary } from '../../types'

export const analyticsFixture = {
  totalViews: 42850,
  totalRequests: 42850,
  uniqueVisitors: 12400,
  viewsToday: 1284,
  requestsToday: 1284,
  uniquesToday: 463,
  viewsPreviousPeriod: 38000,
  uniquesPreviousPeriod: 11200,
  growthRateViews: 12.8,
  growthRateUniques: 10.7,
  cacheHitRatio: 68,
  cacheHitsPreviousPeriod: 62,
  growthRateCacheHits: 6,
  avgDailyViews: 1428,
  avgLatencyMs: 24,
  latencyPreviousPeriod: 30,
  growthRateLatency: -20,
  requestsLast30m: 34,
  activeViewersLast30m: 8,
  camoRatio: 38,
  directRatio: 62,
  peakHour: { hour: 15, views: 280 },
  peakDay: { day: 'Wednesday', views: 1680 },
  timeSeries: [],
  hourlyDistribution: [],
  heatmapGrid: [],
  topCountries: [
    {
      name: 'United States',
      key: 'US',
      code: 'US',
      continent: 'North America',
      continentCode: 'NA',
      flagEmoji: '🇺🇸',
      count: 1850,
      percentage: 42,
    },
    {
      name: 'Brazil',
      key: 'BR',
      code: 'BR',
      continent: 'South America',
      continentCode: 'SA',
      flagEmoji: '🇧🇷',
      count: 980,
      percentage: 22,
    },
  ],
  topContinents: [{ name: 'North America', key: 'NA', code: 'NA', count: 1850, percentage: 42 }],
  topLanguages: [],
  topTimezones: [],
  topSources: [],
  topDevices: [],
  topBrowsers: [],
  topOs: [],
  trafficTypes: [],
  statusCodes: [],
  topProfiles: [
    {
      slug: 'default',
      name: 'Main profile',
      views: 42850,
      uniques: 12400,
      cacheHitRatio: 68,
      avgLatencyMs: 24,
      percentage: 100,
      status: 'active',
    },
  ],
  recentActivity: [],
  range: '30d',
  compareEnabled: true,
  updatedAt: '2026-09-29T12:00:00.000Z',
} satisfies AnalyticsSummary
