import type { GlobalStyles, SavedConfiguration, WidgetInstance } from '../types'

export interface TemplatePreset {
  id: string
  name: string
  description: string
  colors: {
    background: string
    cardBackground: string
    text: string
    accent: string
    border: string
  }
  fontFamily: string
  borderRadius: number
  layout: Array<Omit<WidgetInstance, 'instanceId'>>
}

export const TEMPLATE_PRESETS: Record<string, TemplatePreset> = {
  blank: {
    id: 'blank',
    name: 'Blank Canvas',
    description: 'Empty canvas for complete creative freedom.',
    colors: {
      background: '#060606',
      cardBackground: '#121212',
      text: '#e5e5e5',
      accent: '#c5ff4a',
      border: '#252525',
    },
    fontFamily: "'Inter Tight', sans-serif",
    borderRadius: 0,
    layout: [],
  },
  terminal: {
    id: 'terminal',
    name: 'Terminal',
    description:
      'Retro hacker aesthetic with crisp green accents, command prompt, and ASCII framing.',
    colors: {
      background: '#060606',
      cardBackground: '#121212',
      text: '#e5e5e5',
      accent: '#c5ff4a',
      border: '#252525',
    },
    fontFamily: "'JetBrains Mono', monospace",
    borderRadius: 0,
    layout: [
      {
        widgetId: 'header',
        position: { x: 0, y: 0 },
        size: { width: 800, height: 90 },
        config: {},
        locked: false,
        visible: true,
        zIndex: 1,
      },
      {
        widgetId: 'ascii-art',
        position: { x: 0, y: 106 },
        size: { width: 280, height: 280 },
        config: {
          detail: 'medium',
          cols: 150,
          charset: 'dense',
          edgeEnhance: true,
          lockAspectRatio: true,
        },
        locked: false,
        visible: true,
        zIndex: 2,
      },
      {
        widgetId: 'terminal-info',
        position: { x: 296, y: 106 },
        size: { width: 504, height: 280 },
        config: {},
        locked: false,
        visible: true,
        zIndex: 3,
      },
      {
        widgetId: 'languages',
        position: { x: 0, y: 402 },
        size: { width: 800, height: 140 },
        config: {},
        locked: false,
        visible: true,
        zIndex: 4,
      },
      {
        widgetId: 'repositories',
        position: { x: 0, y: 558 },
        size: { width: 800, height: 300 },
        config: {},
        locked: false,
        visible: true,
        zIndex: 5,
      },
      {
        widgetId: 'footer',
        position: { x: 0, y: 874 },
        size: { width: 800, height: 50 },
        config: {},
        locked: false,
        visible: true,
        zIndex: 6,
      },
    ],
  },
  minimal: {
    id: 'minimal',
    name: 'Minimal Luxe',
    description:
      'Clean editorial presentation with subtle typography, pill badges, and refined spacing.',
    colors: {
      background: '#080808',
      cardBackground: '#121212',
      text: '#ffffff',
      accent: '#f3f4f6',
      border: '#222222',
    },
    fontFamily: "'Inter Tight', sans-serif",
    borderRadius: 8,
    layout: [
      {
        widgetId: 'header',
        position: { x: 0, y: 0 },
        size: { width: 800, height: 96 },
        config: {},
        locked: false,
        visible: true,
        zIndex: 1,
      },
      {
        widgetId: 'bio',
        position: { x: 0, y: 112 },
        size: { width: 800, height: 120 },
        config: {},
        locked: false,
        visible: true,
        zIndex: 2,
      },
      {
        widgetId: 'tech-stack',
        position: { x: 0, y: 248 },
        size: { width: 800, height: 140 },
        config: {},
        locked: false,
        visible: true,
        zIndex: 3,
      },
      {
        widgetId: 'repositories',
        position: { x: 0, y: 404 },
        size: { width: 800, height: 300 },
        config: {},
        locked: false,
        visible: true,
        zIndex: 4,
      },
      {
        widgetId: 'social-media',
        position: { x: 0, y: 720 },
        size: { width: 800, height: 120 },
        config: {},
        locked: false,
        visible: true,
        zIndex: 5,
      },
      {
        widgetId: 'footer',
        position: { x: 0, y: 856 },
        size: { width: 800, height: 48 },
        config: {},
        locked: false,
        visible: true,
        zIndex: 6,
      },
    ],
  },
  dracula: {
    id: 'dracula',
    name: 'Dracula Pro',
    description:
      'Classic dark IDE style with OS control dots (🔴🟡🟢) and a vibrant violet/pink palette.',
    colors: {
      background: '#1e1f29',
      cardBackground: '#282a36',
      text: '#f8f8f2',
      accent: '#ff79c6',
      border: '#44475a',
    },
    fontFamily: "'JetBrains Mono', monospace",
    borderRadius: 8,
    layout: [
      {
        widgetId: 'header',
        position: { x: 0, y: 0 },
        size: { width: 800, height: 96 },
        config: {},
        locked: false,
        visible: true,
        zIndex: 1,
      },
      {
        widgetId: 'avatar',
        position: { x: 0, y: 112 },
        size: { width: 160, height: 160 },
        config: {},
        locked: false,
        visible: true,
        zIndex: 2,
      },
      {
        widgetId: 'bio',
        position: { x: 176, y: 112 },
        size: { width: 624, height: 160 },
        config: {},
        locked: false,
        visible: true,
        zIndex: 3,
      },
      {
        widgetId: 'tech-stack',
        position: { x: 0, y: 288 },
        size: { width: 800, height: 140 },
        config: {},
        locked: false,
        visible: true,
        zIndex: 4,
      },
      {
        widgetId: 'github-readme-stats',
        position: { x: 0, y: 444 },
        size: { width: 390, height: 210 },
        config: {},
        locked: false,
        visible: true,
        zIndex: 5,
      },
      {
        widgetId: 'streak-stats',
        position: { x: 410, y: 444 },
        size: { width: 390, height: 210 },
        config: {},
        locked: false,
        visible: true,
        zIndex: 6,
      },
      {
        widgetId: 'footer',
        position: { x: 0, y: 670 },
        size: { width: 800, height: 48 },
        config: {},
        locked: false,
        visible: true,
        zIndex: 7,
      },
    ],
  },
  synthwave: {
    id: 'synthwave',
    name: 'Synthwave 84',
    description:
      '80s arcade aesthetic with glowing sunset orange, violet grid lines, and neon borders.',
    colors: {
      background: '#12092b',
      cardBackground: '#211342',
      text: '#fecdd3',
      accent: '#ff6b6b',
      border: '#a855f7',
    },
    fontFamily: "'JetBrains Mono', monospace",
    borderRadius: 4,
    layout: [
      {
        widgetId: 'header',
        position: { x: 0, y: 0 },
        size: { width: 800, height: 96 },
        config: {},
        locked: false,
        visible: true,
        zIndex: 1,
      },
      {
        widgetId: 'ascii-art',
        position: { x: 0, y: 112 },
        size: { width: 280, height: 210 },
        config: { detail: 'medium', cols: 150 },
        locked: false,
        visible: true,
        zIndex: 2,
      },
      {
        widgetId: 'bio',
        position: { x: 296, y: 112 },
        size: { width: 504, height: 210 },
        config: {},
        locked: false,
        visible: true,
        zIndex: 3,
      },
      {
        widgetId: 'stats',
        position: { x: 0, y: 338 },
        size: { width: 800, height: 115 },
        config: {},
        locked: false,
        visible: true,
        zIndex: 4,
      },
      {
        widgetId: 'repositories',
        position: { x: 0, y: 469 },
        size: { width: 800, height: 300 },
        config: {},
        locked: false,
        visible: true,
        zIndex: 5,
      },
      {
        widgetId: 'footer',
        position: { x: 0, y: 785 },
        size: { width: 800, height: 50 },
        config: {},
        locked: false,
        visible: true,
        zIndex: 6,
      },
    ],
  },
  tokyonight: {
    id: 'tokyonight',
    name: 'Tokyo Night',
    description:
      'Sleek developer theme with deep blue/purple night sky, cool cyan and neon blue accents.',
    colors: {
      background: '#1a1b26',
      cardBackground: '#24283b',
      text: '#a9b1d6',
      accent: '#7aa2f7',
      border: '#383e5a',
    },
    fontFamily: "'JetBrains Mono', monospace",
    borderRadius: 6,
    layout: [
      {
        widgetId: 'header',
        position: { x: 0, y: 0 },
        size: { width: 800, height: 96 },
        config: {},
        locked: false,
        visible: true,
        zIndex: 1,
      },
      {
        widgetId: 'ascii-art',
        position: { x: 0, y: 112 },
        size: { width: 280, height: 240 },
        config: { detail: 'medium', cols: 150 },
        locked: false,
        visible: true,
        zIndex: 2,
      },
      {
        widgetId: 'bio',
        position: { x: 296, y: 112 },
        size: { width: 504, height: 240 },
        config: {},
        locked: false,
        visible: true,
        zIndex: 3,
      },
      {
        widgetId: 'tech-stack',
        position: { x: 0, y: 368 },
        size: { width: 800, height: 140 },
        config: {},
        locked: false,
        visible: true,
        zIndex: 4,
      },
      {
        widgetId: 'github-readme-stats',
        position: { x: 0, y: 524 },
        size: { width: 390, height: 210 },
        config: {},
        locked: false,
        visible: true,
        zIndex: 5,
      },
      {
        widgetId: 'streak-stats',
        position: { x: 410, y: 524 },
        size: { width: 390, height: 210 },
        config: {},
        locked: false,
        visible: true,
        zIndex: 6,
      },
      {
        widgetId: 'footer',
        position: { x: 0, y: 750 },
        size: { width: 800, height: 48 },
        config: {},
        locked: false,
        visible: true,
        zIndex: 7,
      },
    ],
  },
  gruvbox: {
    id: 'gruvbox',
    name: 'Gruvbox Retro',
    description:
      'Warm, cozy retro theme with high-contrast earthy colors and vintage pumpkin accents.',
    colors: {
      background: '#282828',
      cardBackground: '#3c3836',
      text: '#ebdbb2',
      accent: '#fe8019',
      border: '#504945',
    },
    fontFamily: "'JetBrains Mono', monospace",
    borderRadius: 4,
    layout: [
      {
        widgetId: 'header',
        position: { x: 0, y: 0 },
        size: { width: 800, height: 96 },
        config: {},
        locked: false,
        visible: true,
        zIndex: 1,
      },
      {
        widgetId: 'bio',
        position: { x: 0, y: 112 },
        size: { width: 800, height: 140 },
        config: {},
        locked: false,
        visible: true,
        zIndex: 2,
      },
      {
        widgetId: 'tech-stack',
        position: { x: 0, y: 268 },
        size: { width: 800, height: 140 },
        config: {},
        locked: false,
        visible: true,
        zIndex: 3,
      },
      {
        widgetId: 'repositories',
        position: { x: 0, y: 424 },
        size: { width: 800, height: 300 },
        config: {},
        locked: false,
        visible: true,
        zIndex: 4,
      },
      {
        widgetId: 'social-media',
        position: { x: 0, y: 740 },
        size: { width: 800, height: 120 },
        config: {},
        locked: false,
        visible: true,
        zIndex: 5,
      },
      {
        widgetId: 'footer',
        position: { x: 0, y: 876 },
        size: { width: 800, height: 48 },
        config: {},
        locked: false,
        visible: true,
        zIndex: 6,
      },
    ],
  },
  bento: {
    id: 'bento',
    name: 'Bento Grid',
    description:
      'Clean space-saving grid layout using varying card dimensions to showcase your profile.',
    colors: {
      background: '#09090b',
      cardBackground: '#18181b',
      text: '#f4f4f5',
      accent: '#a1a1aa',
      border: '#27272a',
    },
    fontFamily: "'Inter Tight', sans-serif",
    borderRadius: 12,
    layout: [
      {
        widgetId: 'header',
        position: { x: 0, y: 0 },
        size: { width: 800, height: 90 },
        config: {},
        locked: false,
        visible: true,
        zIndex: 1,
      },
      {
        widgetId: 'avatar',
        position: { x: 0, y: 106 },
        size: { width: 150, height: 150 },
        config: {},
        locked: false,
        visible: true,
        zIndex: 2,
      },
      {
        widgetId: 'bio',
        position: { x: 166, y: 106 },
        size: { width: 634, height: 150 },
        config: {},
        locked: false,
        visible: true,
        zIndex: 3,
      },
      {
        widgetId: 'tech-stack',
        position: { x: 0, y: 272 },
        size: { width: 800, height: 140 },
        config: {},
        locked: false,
        visible: true,
        zIndex: 4,
      },
      {
        widgetId: 'github-readme-stats',
        position: { x: 0, y: 428 },
        size: { width: 390, height: 210 },
        config: {},
        locked: false,
        visible: true,
        zIndex: 5,
      },
      {
        widgetId: 'streak-stats',
        position: { x: 410, y: 428 },
        size: { width: 390, height: 210 },
        config: {},
        locked: false,
        visible: true,
        zIndex: 6,
      },
      {
        widgetId: 'footer',
        position: { x: 0, y: 654 },
        size: { width: 800, height: 48 },
        config: {},
        locked: false,
        visible: true,
        zIndex: 7,
      },
    ],
  },
  githubdark: {
    id: 'githubdark',
    name: 'GitHub Dark Pro',
    description: 'Native developer dashboard layout styling with a clean dark-mode interface.',
    colors: {
      background: '#0d1117',
      cardBackground: '#161b22',
      text: '#c9d1d9',
      accent: '#58a6ff',
      border: '#30363d',
    },
    fontFamily: "'Inter Tight', sans-serif",
    borderRadius: 6,
    layout: [
      {
        widgetId: 'header',
        position: { x: 0, y: 0 },
        size: { width: 800, height: 96 },
        config: {},
        locked: false,
        visible: true,
        zIndex: 1,
      },
      {
        widgetId: 'bio',
        position: { x: 0, y: 112 },
        size: { width: 800, height: 140 },
        config: {},
        locked: false,
        visible: true,
        zIndex: 2,
      },
      {
        widgetId: 'tech-stack',
        position: { x: 0, y: 268 },
        size: { width: 800, height: 140 },
        config: {},
        locked: false,
        visible: true,
        zIndex: 3,
      },
      {
        widgetId: 'repositories',
        position: { x: 0, y: 424 },
        size: { width: 800, height: 300 },
        config: {},
        locked: false,
        visible: true,
        zIndex: 4,
      },
      {
        widgetId: 'footer',
        position: { x: 0, y: 740 },
        size: { width: 800, height: 48 },
        config: {},
        locked: false,
        visible: true,
        zIndex: 5,
      },
    ],
  },
  nordic: {
    id: 'nordic',
    name: 'Nordic Frost',
    description:
      'Clean arctic palette with avatar, bio, live stats, language breakdown, and activity graph in a crisp editorial stack.',
    colors: {
      background: '#2e3440',
      cardBackground: '#3b4252',
      text: '#eceff4',
      accent: '#88c0d0',
      border: '#4c566a',
    },
    fontFamily: "'Inter Tight', sans-serif",
    borderRadius: 6,
    layout: [
      {
        widgetId: 'header',
        position: { x: 0, y: 0 },
        size: { width: 800, height: 90 },
        config: {},
        locked: false,
        visible: true,
        zIndex: 1,
      },
      {
        widgetId: 'avatar',
        position: { x: 0, y: 106 },
        size: { width: 160, height: 160 },
        config: {},
        locked: false,
        visible: true,
        zIndex: 2,
      },
      {
        widgetId: 'bio',
        position: { x: 176, y: 106 },
        size: { width: 624, height: 160 },
        config: {},
        locked: false,
        visible: true,
        zIndex: 3,
      },
      {
        widgetId: 'stats',
        position: { x: 0, y: 282 },
        size: { width: 800, height: 115 },
        config: {},
        locked: false,
        visible: true,
        zIndex: 4,
      },
      {
        widgetId: 'languages',
        position: { x: 0, y: 413 },
        size: { width: 800, height: 140 },
        config: {},
        locked: false,
        visible: true,
        zIndex: 5,
      },
      {
        widgetId: 'activity-graph',
        position: { x: 0, y: 569 },
        size: { width: 800, height: 210 },
        config: {},
        locked: false,
        visible: true,
        zIndex: 6,
      },
      {
        widgetId: 'footer',
        position: { x: 0, y: 795 },
        size: { width: 800, height: 48 },
        config: {},
        locked: false,
        visible: true,
        zIndex: 7,
      },
    ],
  },
  hackerspace: {
    id: 'hackerspace',
    name: 'Hackerspace',
    description:
      'Deep hacker aesthetic with ASCII text art banner, neofetch terminal info, language chart, developer quote, and a neon divider.',
    colors: {
      background: '#0a0f0a',
      cardBackground: '#0f1a0f',
      text: '#00ff41',
      accent: '#00ff41',
      border: '#1a3a1a',
    },
    fontFamily: "'JetBrains Mono', monospace",
    borderRadius: 0,
    layout: [
      {
        widgetId: 'header',
        position: { x: 0, y: 0 },
        size: { width: 800, height: 90 },
        config: {},
        locked: false,
        visible: true,
        zIndex: 1,
      },
      {
        widgetId: 'ascii-text',
        position: { x: 0, y: 106 },
        size: { width: 800, height: 120 },
        config: { customText: 'HACK THE PLANET', fontSize: 14 },
        locked: false,
        visible: true,
        zIndex: 2,
      },
      {
        widgetId: 'terminal-info',
        position: { x: 0, y: 242 },
        size: { width: 800, height: 280 },
        config: {},
        locked: false,
        visible: true,
        zIndex: 3,
      },
      {
        widgetId: 'languages',
        position: { x: 0, y: 538 },
        size: { width: 800, height: 140 },
        config: {},
        locked: false,
        visible: true,
        zIndex: 4,
      },
      {
        widgetId: 'divider',
        position: { x: 0, y: 694 },
        size: { width: 800, height: 24 },
        config: {},
        locked: false,
        visible: true,
        zIndex: 5,
      },
      {
        widgetId: 'readme-quotes',
        position: { x: 0, y: 734 },
        size: { width: 800, height: 140 },
        config: {},
        locked: false,
        visible: true,
        zIndex: 6,
      },
      {
        widgetId: 'footer',
        position: { x: 0, y: 890 },
        size: { width: 800, height: 48 },
        config: {},
        locked: false,
        visible: true,
        zIndex: 7,
      },
    ],
  },
  contributor: {
    id: 'contributor',
    name: 'OSS Contributor',
    description:
      'Open-source showcase with live stats, language breakdown, GitHub trophies, animated contribution snake, and social links.',
    colors: {
      background: '#0d1117',
      cardBackground: '#161b22',
      text: '#c9d1d9',
      accent: '#3fb950',
      border: '#21262d',
    },
    fontFamily: "'Inter Tight', sans-serif",
    borderRadius: 6,
    layout: [
      {
        widgetId: 'header',
        position: { x: 0, y: 0 },
        size: { width: 800, height: 90 },
        config: {},
        locked: false,
        visible: true,
        zIndex: 1,
      },
      {
        widgetId: 'bio',
        position: { x: 0, y: 106 },
        size: { width: 800, height: 120 },
        config: {},
        locked: false,
        visible: true,
        zIndex: 2,
      },
      {
        widgetId: 'stats',
        position: { x: 0, y: 242 },
        size: { width: 390, height: 115 },
        config: {},
        locked: false,
        visible: true,
        zIndex: 3,
      },
      {
        widgetId: 'languages',
        position: { x: 410, y: 242 },
        size: { width: 390, height: 140 },
        config: {},
        locked: false,
        visible: true,
        zIndex: 4,
      },
      {
        widgetId: 'profile-trophy',
        position: { x: 0, y: 398 },
        size: { width: 800, height: 210 },
        config: {},
        locked: false,
        visible: true,
        zIndex: 5,
      },
      {
        widgetId: 'contribution-snake',
        position: { x: 0, y: 624 },
        size: { width: 800, height: 160 },
        config: {},
        locked: false,
        visible: true,
        zIndex: 6,
      },
      {
        widgetId: 'social-media',
        position: { x: 0, y: 800 },
        size: { width: 800, height: 100 },
        config: {},
        locked: false,
        visible: true,
        zIndex: 7,
      },
      {
        widgetId: 'footer',
        position: { x: 0, y: 916 },
        size: { width: 800, height: 48 },
        config: {},
        locked: false,
        visible: true,
        zIndex: 8,
      },
    ],
  },
  galaxy: {
    id: 'galaxy',
    name: 'Deep Space',
    description:
      'Nebula-dark theme with ASCII avatar art, compact stats, 31-day activity graph, featured repos, and a profile views counter.',
    colors: {
      background: '#06010f',
      cardBackground: '#100820',
      text: '#d0c8f0',
      accent: '#c084fc',
      border: '#2d1a5e',
    },
    fontFamily: "'JetBrains Mono', monospace",
    borderRadius: 4,
    layout: [
      {
        widgetId: 'header',
        position: { x: 0, y: 0 },
        size: { width: 800, height: 90 },
        config: {},
        locked: false,
        visible: true,
        zIndex: 1,
      },
      {
        widgetId: 'ascii-art',
        position: { x: 0, y: 106 },
        size: { width: 240, height: 200 },
        config: {
          detail: 'medium',
          cols: 120,
          charset: 'dense',
          edgeEnhance: true,
          lockAspectRatio: true,
        },
        locked: false,
        visible: true,
        zIndex: 2,
      },
      {
        widgetId: 'stats',
        position: { x: 256, y: 106 },
        size: { width: 544, height: 115 },
        config: {},
        locked: false,
        visible: true,
        zIndex: 3,
      },
      {
        widgetId: 'views-counter',
        position: { x: 256, y: 237 },
        size: { width: 544, height: 75 },
        config: {},
        locked: false,
        visible: true,
        zIndex: 4,
      },
      {
        widgetId: 'activity-graph',
        position: { x: 0, y: 322 },
        size: { width: 800, height: 210 },
        config: {},
        locked: false,
        visible: true,
        zIndex: 5,
      },
      {
        widgetId: 'repositories',
        position: { x: 0, y: 548 },
        size: { width: 800, height: 300 },
        config: {},
        locked: false,
        visible: true,
        zIndex: 6,
      },
      {
        widgetId: 'footer',
        position: { x: 0, y: 864 },
        size: { width: 800, height: 48 },
        config: {},
        locked: false,
        visible: true,
        zIndex: 7,
      },
    ],
  },
  devcard: {
    id: 'devcard',
    name: 'Dev Card',
    description:
      'Sharp editorial developer identity card: avatar, bio, full tech stack, GitHub stats, and advanced metrics infographic.',
    colors: {
      background: '#080808',
      cardBackground: '#111111',
      text: '#e8e8e8',
      accent: '#facc15',
      border: '#1c1c1c',
    },
    fontFamily: "'Inter Tight', sans-serif",
    borderRadius: 8,
    layout: [
      {
        widgetId: 'header',
        position: { x: 0, y: 0 },
        size: { width: 800, height: 90 },
        config: {},
        locked: false,
        visible: true,
        zIndex: 1,
      },
      {
        widgetId: 'avatar',
        position: { x: 0, y: 106 },
        size: { width: 180, height: 180 },
        config: {},
        locked: false,
        visible: true,
        zIndex: 2,
      },
      {
        widgetId: 'bio',
        position: { x: 196, y: 106 },
        size: { width: 604, height: 180 },
        config: {},
        locked: false,
        visible: true,
        zIndex: 3,
      },
      {
        widgetId: 'tech-stack',
        position: { x: 0, y: 302 },
        size: { width: 800, height: 140 },
        config: {},
        locked: false,
        visible: true,
        zIndex: 4,
      },
      {
        widgetId: 'stats',
        position: { x: 0, y: 458 },
        size: { width: 390, height: 115 },
        config: {},
        locked: false,
        visible: true,
        zIndex: 5,
      },
      {
        widgetId: 'metrics-card',
        position: { x: 410, y: 458 },
        size: { width: 390, height: 220 },
        config: {},
        locked: false,
        visible: true,
        zIndex: 6,
      },
      {
        widgetId: 'footer',
        position: { x: 0, y: 694 },
        size: { width: 800, height: 48 },
        config: {},
        locked: false,
        visible: true,
        zIndex: 7,
      },
    ],
  },
}

export function createConfiguration(
  githubId: number,
  username: string,
  templateId = 'terminal',
  profileSlug = 'default',
  profileName = 'Default'
): SavedConfiguration {
  const preset = TEMPLATE_PRESETS[templateId] || TEMPLATE_PRESETS.terminal

  const widgets: WidgetInstance[] = preset.layout.map((item, index) => ({
    ...item,
    instanceId: `widget_${Date.now()}_${index}`,
    name: `${item.widgetId.charAt(0).toUpperCase() + item.widgetId.slice(1)} Widget`,
  }))

  const globalStyles: GlobalStyles = {
    backgroundColor: preset.colors.background,
    textColor: preset.colors.text,
    accentColor: preset.colors.accent,
    borderColor: preset.colors.border,
    fontFamily: preset.fontFamily,
    borderRadius: preset.borderRadius,
    padding: 24,
    themeMode: 'dark',
    templateStyle: preset.id,
  }

  return {
    version: 1,
    githubId,
    username,
    profileSlug,
    profileName,
    templateId,
    widgets,
    globalStyles,
    metadata: {
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      schemaVersion: 1,
    },
  }
}
